### PR TITLE
Add ActiveJob support

### PR DESCRIPTION
**Pull request by piotrkaczmarek**
Hello everyone,

Here's my attempt at adding ActiveJob support. I would be happy to hear your feedback. We use carrierwave_backgrounder at our project and I've tested this PR with sidekiq as an ActiveJob queue_adapter.

Cheers,
Piotr

### CODE REVIEW

**Comment by philipgiuliani** [comment]
Hi. I just tried the branch (with a custom Job). I am using the process in background method.
Unforunatly the image is directly processed (i tested it by stopping my sidekiq worker).

I have one enqueued Job:
ImageProcessingJob ["Image", "171", "image"]

But all versions have already been created (i check the uploads directory). When i start sidekiq the job is processing without any errors. No idea whats happening.

**Comment by piotrkaczmarek** [comment]
@philipgiuliani I've just rebased it. Please check if the problem still persist. I'll now try it myself and try to debug it.

**Comment by piotrkaczmarek** [comment]
I've created clean project to test this PR: https://github.com/piotrkaczmarek/backgrounder_test but it works as expected. @philipgiuliani could you please take a look and see if you can reproduce the issue?

**Comment by kipcole9** [comment]
Any chance of this PR being merged and committed?

**Comment by lardawge** [comment]
Yup

**Comment by lardawge** [comment]
I am working on a project that I can use it on so will confirm things are working as expected before I release...

**Comment by kipcole9** [comment]
Thanks!  I am working on a project and will run from master to also confirm things are as expected.

**Comment by philister** [comment]
This broke the delayed_job support (`c.backend :delayed_job`) for us. With overridden worker, as in readme, the following error occurs:
```
ArgumentError (wrong number of arguments (given 3, expected 0)):
  bundler/gems/carrierwave_backgrounder-460394b0e2c0/lib/backgrounder/workers/base.rb:9:in `initialize'
```
worker:
```RUBY
class MyParanoidWorker < ::CarrierWave::Workers::ProcessAsset
  def error(job, exception)
    # nothing
  end
end
```
model:
```RUBY
mount_uploader :picture, MyUploader
process_in_background :picture, MyParanoidWorker
```
 Without overridden worker, all went fine.
I was not able to write a test for this "overridden worker" feature.

I like the ActiveJob-Feature, but we have overridden workers and don't want to refactor them atm.

**Pull request merged**
