### PR TITLE
Upgrade to Carrierwave 1.0.0

### PR DESCRIPTION
**Pull request by kevin-jj**
```ruby
/Users/liujun/.rbenv/versions/2.4.0/bin/ruby -I/Users/liujun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib:/Users/liujun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib /Users/liujun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*/\*_spec.rb -c -f progress -r ./spec/spec_helper.rb
............................................................

Finished in 0.0703 seconds (files took 0.49761 seconds to load)
60 examples, 0 failures
```

### CODE REVIEW

**Comment by kevin-jj** [comment]
@lardawge @piotrkaczmarek @kntmrkm  

would be great to merge this PR and release a new version.

**Comment by ErvalhouS** [comment]
Branch working OK, besides CI failure.

**Comment by kevin-jj** [comment]
dropping support of Ruby 1.9.3 will lead to CI success. @ErvalhouS

**Comment by ErvalhouS** [comment]
Changing `mime-types` version requirement to `~>2.99` should resolve also, but this version will reach full end of life on 2017-11-21. Better solution would be, indeed, dropping 1.9.3 support, since:

>  Users are encouraged to upgrade to mime-types 3.x as soon as is practical. mime-types 3.x requires Ruby 2.0 compatibility and a simpler licensing scheme.

**Comment by kevin-jj** [comment]
@ErvalhouS  It's been green.

**Comment by mountriv99** [comment]
would be great to have this merged

**Comment by lardawge** [comment]
Merged. I will release a new version. I also think dropping support at this point for 1.9.3 make sense with other changes I want to make to simplify things and add activejob support. For now I will release as is.

**Comment by mountriv99** [comment]
@lardawge  appreciate that, thanks

**Comment by itsmeduncan** [comment]
@lardawge Any updates on a new release?

**Comment by davidwparker** [comment]
New Release? Thanks!

**Comment by nj** [comment]
@lardawge Dropping `1.9.3` would make perfectly sense, as `CarrierWave` dropped it by `1.0.0` - or more precisely, [back in 2015](https://github.com/carrierwaveuploader/carrierwave/commit/2517d66) :astonished:

So should be safe to drop the legacy version in `carrierwave_backgrounder` as well :wink:

**Comment by davidwparker** [comment]
Gonna ping @lardawge on this again. Any chance at a release? Thanks!

**Comment by PikachuEXE** [comment]
@lardawge Please release a new version thanks~

**Pull request merged**
