### PR TITLE
Bump changes to support carrierwave version ref 6aca9268.

### PR DESCRIPTION
**Pull request by majioa**

### CODE REVIEW

**Comment by majioa** [comment]
Related to #234

**Comment by majioa** [comment]
@lardawge are you visiting here? =)

**Comment by kovalevsky** [comment]
Nice job!
The PR seems solve bunch of issues: #246, #200, #195 
@lardawge could you review and merge it?

**Comment by IlkhamGaysin** [comment]
@lardawge sweet pr ;)

**Pull request merged**
